language: python
notifications:
  email: false
env:
  global:
  - secure: "PUjnq3yn84H9fxhceq9JmykWywz9pCoy4j/+GruTQsO1OCuZEcvvMWDmqEzSDzOLL7rb5hE9GXV9YJaC9yiTpl6nhRojL710lEK+9jK+cv49EA/lvWaxSzicdCiEDkDjbhKmrTZtfprCLKIXC2C843vFSOspLuyMiMBquKBsecY43lw+Z9ZQePxbhNzeIDp8wbsW+gIAteI7BjT/fZ+KroGdkyyQMfHTakxNZCJEK38RwR3OuAaZ931P3XXuh7fnEEIHcTbvd7gSfiokmkGL/6vMBTids3uzOnv+WAH6zSiy9+fAPnZqOe06/+1sAg2Iu0/GFLHCXaHREpRyFb7CBQ2tJ5ZnvETahMsbA3cZc67vhs1Zg56PMhDpB0Hvg3vksV4FipA3xJgExsxVvAahvEiq3D6rs6yDfrNgbRi+Ha/zQ9EP/eNWqWsVnDMG0yce6t6xbCXBj9/J5UBYnHiY6E54V9SM3/9mCnM79Z2qOCDZEoJzGENNDzpggeNa0F5ihdK2AZ5HzncX+H69jZM4azFlqKxdW3d9RRafkggnJ/VMInHciJKu+4VuNWRn8IHKCS2q55n4gJtgeJdUkzjjAv4zSNpfX70X66O26asqJWsrGMXyYyPyVxmD3PSx7ZsdHoU2OnqzH8nSv+tlIM0fsW8551Zka+dmsmC3UzG88RE="
python:
# Dummy versions - we will use miniconda
- "2.7"
- "3.4"
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq libfftw3-3 libfftw3-dev
- wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
- chmod +x miniconda.sh
- ./miniconda.sh -b
- export PATH=/home/travis/miniconda/bin:$PATH
- conda update --yes conda
- travis_retry conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy scipy cffi
- travis_retry pip install .
install:
- travis_retry pip install coverage
- travis_retry pip install coveralls
- pip freeze
script:
  - coverage run --source=odtbrain tests/runtests.py
  - coverage report -m
after_success:
  coveralls --verbose
