language: python
notifications:
  email: false
env:
  global:
  - GH_REF: github.com/paulmueller/ODTbrain.git
  - secure: SIZHw7XSgIr5vgUPrTf8vdzaojnx6UegOetP5r/G6TUdOqk8knm+jxEi1Dzy2cL+O2VZSwcLwBZNGLsCdslfxrMw8VzfXLQTGcEIWgj8SERMHTRPU0QmgiMssSYrzbSdsQQXaaUpvZBwqRb+HT56SXdItwM55POkQV52VNpAEQYRC1IG2wpJjCAPtnfuFvEKr2YRGRWSQCo08tcDurazMKyEL4ZdFyzbK0oo3uIGBiQZRHyQ+2qBgMYLSO840rUl+AR98+34IJViZnyk34lGmSjFF1oDn8o74eO4wPW8VYtnmgk02NKmI2Dl4jOz7xHurAcB2lFGoApUaPug/l5EWi6YdgM0zIAQ85UCFu04yPQjTaZMygQFiwgAUT6MfD0vTFlHlcr2yFjeuPE1+DJepSihqCGKiBfIejLUYOtD9VKn5exqgGaJoDB0rTCEiQvucVSHXNR2ia5yegzU7MQll6ri/8PFfUmKqZSTLvOl16kMinOxjPB8f49C3iH0DFLgmOWLGiawrsZoq1WW//Yl64yRdlb21t3/IHMczmdpJDgq7K5G6bRaDhmk1MCAaPn/4PhSV8F02tKS/vICCuh+27UC0A4euRSrJnOfV8rvcDSPov9F3aQeXgVhXmpS0WyP3fHU3/IHJ66AG4rM2FS51O/tKLVPt8KcueRvyrZ7W88=
python:
- '2.7'
- '3.4'
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq libfftw3-3 libfftw3-dev
- wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
- chmod +x miniconda.sh
- ./miniconda.sh -b
- export PATH=/home/travis/miniconda/bin:$PATH
- conda update --yes conda
- travis_retry conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy scipy cffi
  sphinx
- travis_retry pip install .
install:
- travis_retry pip install coverage
- travis_retry pip install coveralls
- pip freeze
script:
- coverage run --source=odtbrain tests/runtests.py
- coverage report -m
after_success:
- coveralls --verbose
- if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then pip install numpydoc; fi
- if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then python doc/deploy_ghpages.py; fi
