clone_depth: 256

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

environment:
  matrix:
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"

install:
  - "set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  # Check that we have the expected version and architecture for Python
  - "python --version"
  # install
  - "appveyor-retry pip install wheel"
  - "appveyor-retry pip install . --only-binary pyfftw"
  - "python -m pip freeze"

build: off

test_script:
  - "appveyor-retry pip install coverage"
  - "appveyor-retry pip install codecov"
  - "coverage run --source=odtbrain ./setup.py test"
  - "coverage report -m"
  # Allow codecov to fail
  - "codecov || exit 0"
